"""add drunk_saw_role_id field to game

Revision ID: 2b1a1c3a2903
Revises: e5d6fe48ab95
Create Date: 2024-08-19 02:04:20.971904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b1a1c3a2903"
down_revision: Union[str, None] = "e5d6fe48ab95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("drunk_saw_role_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "games", "roles", ["drunk_saw_role_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "games", type_="foreignkey")
    op.drop_column("games", "drunk_saw_role_id")
    # ### end Alembic commands ###
