"""add homebrew bool to role model

Revision ID: a2ee8ec5a5f7
Revises: 2b1a1c3a2903
Create Date: 2024-12-31 15:32:49.576635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ee8ec5a5f7'
down_revision: Union[str, None] = '2b1a1c3a2903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('homebrew', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'homebrew')
    # ### end Alembic commands ###
